#ifndef LANG_HPP
#define LANG_HPP

typedef enum
{
    WRITE_DATA,
    READ_DATA,
    GENERATE_PASSWORD,
    CHANGE_CYPHER_KEY,
    WIPE_DATA,
    ABOUT_PROGRAM,
    CYPHER_KEY,
    NEW_ENTRY,
    ENTRY_NAME,
    OPT,
    ENTRY_DATA,
    ENTER_DATA,
    CANCEL,
    FIND_BY_NAME,
    DATA,
    PASSWORD_NAME,
    PASSWORD_LENGTH,
    DEFAULT_PASSWORD_LENGTH,
    PASSWORD_MANAGER,
    ARE_YOU_SURE,
    NEW_CYPHER_KEY,
    INFO,
    OP_SUCCESS,
    ERR,
    ERR_COULD_NOT_CONVERT_PASSWORD_LENGTH,
    ERR_THIS_OPERATION_REQUIRES_A_CYPHER_KEY,
    count
} lang_string_kind;

#endif // LANG_HPP
